name: shipit
on:
  push:
    branches:
      - master
jobs:
  shipit:
    name: shipit
    runs-on: ubuntu-latest
    steps:
      - uses: kevinrobayna/shipit@v2.0.0
        id: shipit
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          PR_FILTER: "auto_merge"

      - run: echo 'Merge conflicts found!'
        if: ${{ steps.shipit.outputs.conflicted }}

      - run: echo 'No merge conflicts'
        if: ${{ !steps.shipit.outputs.conflicted }}
