name: Tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install dependencies
        run: yarn install --dev
      - name: Lint files
        run: yarn run lint
      - name: Run tests
        run: yarn run test
        env:
          CI: true
      - name: build image
        uses: ./
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          DRY_RUN: "true"
          PR_FILTER: "labelled"
          PR_LABELS: "autoupdate,dummy label,anotherLabel"
